apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: marline-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: marlinejohn/result-app:latest
          ports:
            - containerPort: 80
          env:
            - name: PG_HOST
              value: postgres
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: PG_DATABASE
              value: votes # Or whatever DB name your app expects
            - name: PG_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: marline-voting-app
spec:
  selector:
    app: result
  ports:
    - port: 80
      targetPort: 80
